-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_rgr_bgb_kernel_ap_uint_10_5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (9 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of ISPPipeline_accel_rgr_bgb_kernel_ap_uint_10_5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";

attribute shreg_extract : string;
    signal ret_V_23_fu_198_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_23_reg_378 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ret_V_24_fu_212_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_24_reg_383 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln97_1_fu_258_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln97_1_reg_388 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln98_fu_291_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln98_reg_393 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_reg_398 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln98_2_reg_403 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln232_1_fu_124_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_fu_120_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_3_fu_138_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_2_fu_134_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_25_fu_142_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_fu_152_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_7_fu_156_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1541_fu_160_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_8_fu_166_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln232_4_fu_148_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_26_fu_170_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1541_9_fu_180_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_10_fu_184_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1541_2_fu_188_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_11_fu_194_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln1541_6_fu_176_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln232_6_fu_208_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_5_fu_204_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1_fu_222_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_fu_128_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln_fu_234_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln97_1_fu_244_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln96_1_fu_218_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln97_fu_248_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln97_2_fu_254_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln97_fu_230_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln_fu_264_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln97_3_fu_275_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln96_fu_271_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln97_2_fu_278_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln97_4_fu_284_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln98_fu_288_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln98_1_fu_315_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln98_1_fu_320_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln98_fu_330_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln98_1_fu_334_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln98_1_fu_344_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln98_2_fu_338_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln98_2_fu_347_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_fu_351_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_42_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln97_fu_358_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln99_fu_370_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal p_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read1_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read4_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read5_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read6_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read7_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read8_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read9_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal p_read10_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (12 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln97_1_reg_388 <= add_ln97_1_fu_258_p2;
                ret_V_23_reg_378 <= ret_V_23_fu_198_p2;
                ret_V_24_reg_383 <= ret_V_24_fu_212_p2;
                sub_ln98_reg_393 <= sub_ln98_fu_291_p2;
                tmp_reg_398 <= sub_ln98_fu_291_p2(14 downto 14);
                trunc_ln98_2_reg_403 <= sub_ln98_fu_291_p2(14 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln99_fu_370_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read10_int_reg <= p_read10;
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read4_int_reg <= p_read4;
                p_read5_int_reg <= p_read5;
                p_read6_int_reg <= p_read6;
                p_read7_int_reg <= p_read7;
                p_read8_int_reg <= p_read8;
                p_read9_int_reg <= p_read9;
                p_read_int_reg <= p_read;
            end if;
        end if;
    end process;
    add_ln1541_2_fu_188_p2 <= std_logic_vector(unsigned(zext_ln1541_9_fu_180_p1) + unsigned(zext_ln1541_10_fu_184_p1));
    add_ln1541_fu_160_p2 <= std_logic_vector(unsigned(zext_ln1541_fu_152_p1) + unsigned(zext_ln1541_7_fu_156_p1));
    add_ln97_1_fu_258_p2 <= std_logic_vector(unsigned(zext_ln97_2_fu_254_p1) + unsigned(zext_ln97_fu_230_p1));
    add_ln97_2_fu_278_p2 <= std_logic_vector(unsigned(zext_ln97_3_fu_275_p1) + unsigned(zext_ln96_fu_271_p1));
    add_ln97_fu_248_p2 <= std_logic_vector(unsigned(zext_ln97_1_fu_244_p1) + unsigned(zext_ln96_1_fu_218_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln99_fu_370_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln99_fu_370_p3;
        else 
            ap_return <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    lshr_ln_fu_234_p4 <= ret_V_fu_128_p2(10 downto 1);
    res_fu_351_p3 <= 
        sub_ln98_2_fu_338_p2 when (tmp_reg_398(0) = '1') else 
        zext_ln98_2_fu_347_p1;
    ret_V_23_fu_198_p2 <= std_logic_vector(unsigned(zext_ln1541_11_fu_194_p1) + unsigned(zext_ln1541_6_fu_176_p1));
    ret_V_24_fu_212_p2 <= std_logic_vector(unsigned(zext_ln232_6_fu_208_p1) + unsigned(zext_ln232_5_fu_204_p1));
    ret_V_25_fu_142_p2 <= std_logic_vector(unsigned(zext_ln232_3_fu_138_p1) + unsigned(zext_ln232_2_fu_134_p1));
    ret_V_26_fu_170_p2 <= std_logic_vector(unsigned(zext_ln1541_8_fu_166_p1) + unsigned(zext_ln232_4_fu_148_p1));
    ret_V_fu_128_p2 <= std_logic_vector(unsigned(zext_ln232_1_fu_124_p1) + unsigned(zext_ln232_fu_120_p1));
    select_ln99_fu_370_p3 <= 
        ap_const_lv13_0 when (tmp_42_fu_362_p3(0) = '1') else 
        trunc_ln97_fu_358_p1;
        sext_ln98_1_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_2_reg_403),13));

        sext_ln98_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_1_fu_320_p4),13));

    shl_ln1_fu_222_p3 <= (p_read5_int_reg & ap_const_lv2_0);
    shl_ln_fu_264_p3 <= (ret_V_24_reg_383 & ap_const_lv2_0);
    sub_ln98_1_fu_315_p2 <= std_logic_vector(unsigned(ap_const_lv15_0) - unsigned(sub_ln98_reg_393));
    sub_ln98_2_fu_338_p2 <= std_logic_vector(unsigned(ap_const_lv14_0) - unsigned(zext_ln98_1_fu_334_p1));
    sub_ln98_fu_291_p2 <= std_logic_vector(unsigned(zext_ln97_4_fu_284_p1) - unsigned(zext_ln98_fu_288_p1));
    tmp_42_fu_362_p3 <= res_fu_351_p3(13 downto 13);
    trunc_ln97_fu_358_p1 <= res_fu_351_p3(13 - 1 downto 0);
    trunc_ln98_1_fu_320_p4 <= sub_ln98_1_fu_315_p2(14 downto 3);
    zext_ln1541_10_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read9_int_reg),11));
    zext_ln1541_11_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1541_2_fu_188_p2),13));
    zext_ln1541_6_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_26_fu_170_p2),13));
    zext_ln1541_7_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read7_int_reg),11));
    zext_ln1541_8_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1541_fu_160_p2),12));
    zext_ln1541_9_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read8_int_reg),11));
    zext_ln1541_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read3_int_reg),11));
    zext_ln232_1_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read10_int_reg),11));
    zext_ln232_2_fu_134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read1_int_reg),11));
    zext_ln232_3_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read2_int_reg),11));
    zext_ln232_4_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_25_fu_142_p2),12));
    zext_ln232_5_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read4_int_reg),11));
    zext_ln232_6_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read6_int_reg),11));
    zext_ln232_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read_int_reg),11));
    zext_ln96_1_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read5_int_reg),11));
    zext_ln96_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_264_p3),14));
    zext_ln97_1_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_234_p4),11));
    zext_ln97_2_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln97_fu_248_p2),13));
    zext_ln97_3_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln97_1_reg_388),14));
    zext_ln97_4_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln97_2_fu_278_p2),15));
    zext_ln97_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_222_p3),13));
    zext_ln98_1_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln98_fu_330_p1),14));
    zext_ln98_2_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln98_1_fu_344_p1),14));
    zext_ln98_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_23_reg_378),15));
end behav;
