-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_gaincontrol_3_13_1080_1920_1_Pipeline_ColLoop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgInput2_data239_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    imgInput2_data239_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput2_data239_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput2_data239_empty_n : IN STD_LOGIC;
    imgInput2_data239_read : OUT STD_LOGIC;
    gain_out_data240_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    gain_out_data240_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    gain_out_data240_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    gain_out_data240_full_n : IN STD_LOGIC;
    gain_out_data240_write : OUT STD_LOGIC;
    p_read1 : IN STD_LOGIC_VECTOR (10 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (0 downto 0);
    conv3_i11_i_i214_i : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i11_i_i152_i : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of ISPPipeline_accel_gaincontrol_3_13_1080_1920_1_Pipeline_ColLoop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln90_fu_121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal imgInput2_data239_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gain_out_data240_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv3_i11_i_i152_i_cast_fu_105_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal conv3_i11_i_i152_i_cast_reg_260 : STD_LOGIC_VECTOR (25 downto 0);
    signal conv3_i11_i_i214_i_cast_fu_109_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal conv3_i11_i_i214_i_cast_reg_265 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln1073_fu_133_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1073_reg_274 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1073_reg_274_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1073_reg_274_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1073_reg_274_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_reg_280 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_V_reg_280_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_V_reg_280_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln232_fu_142_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal t_V_4_fu_225_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal t_V_4_reg_291 : STD_LOGIC_VECTOR (9 downto 0);
    signal j_V_fu_64 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_V_6_fu_127_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_V_5 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_150_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_233_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_150_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln9_fu_165_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln47_fu_159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln9_fu_165_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_45_fu_182_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_240_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_45_fu_182_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln260_3_fu_197_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln47_1_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln260_3_fu_197_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln112_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_fu_174_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln116_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_fu_206_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal t_V_2_fu_214_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_233_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_233_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_240_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_240_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_233_ce : STD_LOGIC;
    signal grp_fu_240_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ISPPipeline_accel_mul_mul_16ns_10ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component ISPPipeline_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_mul_16ns_10ns_26_4_1_U70 : component ISPPipeline_accel_mul_mul_16ns_10ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_233_p0,
        din1 => grp_fu_233_p1,
        ce => grp_fu_233_ce,
        dout => grp_fu_233_p2);

    mul_mul_16ns_10ns_26_4_1_U71 : component ISPPipeline_accel_mul_mul_16ns_10ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_240_p0,
        din1 => grp_fu_240_p1,
        ce => grp_fu_240_ce,
        dout => grp_fu_240_p2);

    flow_control_loop_pipe_sequential_init_U : component ISPPipeline_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    j_V_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln90_fu_121_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_V_fu_64 <= j_V_6_fu_127_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_V_fu_64 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    conv3_i11_i_i152_i_cast_reg_260(15 downto 0) <= conv3_i11_i_i152_i_cast_fu_105_p1(15 downto 0);
                    conv3_i11_i_i214_i_cast_reg_265(15 downto 0) <= conv3_i11_i_i214_i_cast_fu_109_p1(15 downto 0);
                tmp_V_reg_280 <= imgInput2_data239_dout;
                trunc_ln1073_reg_274_pp0_iter1_reg <= trunc_ln1073_reg_274;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                t_V_4_reg_291 <= t_V_4_fu_225_p3;
                tmp_V_reg_280_pp0_iter2_reg <= tmp_V_reg_280;
                tmp_V_reg_280_pp0_iter3_reg <= tmp_V_reg_280_pp0_iter2_reg;
                trunc_ln1073_reg_274_pp0_iter2_reg <= trunc_ln1073_reg_274_pp0_iter1_reg;
                trunc_ln1073_reg_274_pp0_iter3_reg <= trunc_ln1073_reg_274_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln90_fu_121_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln1073_reg_274 <= trunc_ln1073_fu_133_p1;
            end if;
        end if;
    end process;
    conv3_i11_i_i152_i_cast_reg_260(25 downto 16) <= "0000000000";
    conv3_i11_i_i214_i_cast_reg_265(25 downto 16) <= "0000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln116_fu_221_p2 <= (trunc_ln1073_reg_274_pp0_iter3_reg and trunc_ln);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, imgInput2_data239_empty_n, gain_out_data240_full_n)
    begin
                ap_block_pp0_stage0_01001 <= (((gain_out_data240_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((imgInput2_data239_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, imgInput2_data239_empty_n, gain_out_data240_full_n)
    begin
                ap_block_pp0_stage0_11001 <= (((gain_out_data240_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((imgInput2_data239_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, imgInput2_data239_empty_n, gain_out_data240_full_n)
    begin
                ap_block_pp0_stage0_subdone <= (((gain_out_data240_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((imgInput2_data239_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(imgInput2_data239_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (imgInput2_data239_empty_n = ap_const_logic_0);
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp0_stage0_iter5_assign_proc : process(gain_out_data240_full_n)
    begin
                ap_block_state6_pp0_stage0_iter5 <= (gain_out_data240_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln90_fu_121_p2)
    begin
        if (((icmp_ln90_fu_121_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_V_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_V_fu_64, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_V_5 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_j_V_5 <= j_V_fu_64;
        end if; 
    end process;

    conv3_i11_i_i152_i_cast_fu_105_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv3_i11_i_i152_i),26));
    conv3_i11_i_i214_i_cast_fu_109_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv3_i11_i_i214_i),26));

    gain_out_data240_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, gain_out_data240_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            gain_out_data240_blk_n <= gain_out_data240_full_n;
        else 
            gain_out_data240_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    gain_out_data240_din <= t_V_4_reg_291;

    gain_out_data240_write_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            gain_out_data240_write <= ap_const_logic_1;
        else 
            gain_out_data240_write <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_233_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_233_ce <= ap_const_logic_1;
        else 
            grp_fu_233_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_233_p0 <= conv3_i11_i_i214_i_cast_reg_265(16 - 1 downto 0);
    grp_fu_233_p1 <= zext_ln232_fu_142_p1(10 - 1 downto 0);

    grp_fu_240_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_240_ce <= ap_const_logic_1;
        else 
            grp_fu_240_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_240_p0 <= conv3_i11_i_i152_i_cast_reg_260(16 - 1 downto 0);
    grp_fu_240_p1 <= zext_ln232_fu_142_p1(10 - 1 downto 0);
    icmp_ln47_1_fu_191_p2 <= "0" when (tmp_45_fu_182_p4 = ap_const_lv9_0) else "1";
    icmp_ln47_fu_159_p2 <= "0" when (tmp_fu_150_p4 = ap_const_lv9_0) else "1";
    icmp_ln90_fu_121_p2 <= "1" when (ap_sig_allocacmp_j_V_5 = p_read1) else "0";

    imgInput2_data239_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, imgInput2_data239_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgInput2_data239_blk_n <= imgInput2_data239_empty_n;
        else 
            imgInput2_data239_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    imgInput2_data239_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgInput2_data239_read <= ap_const_logic_1;
        else 
            imgInput2_data239_read <= ap_const_logic_0;
        end if; 
    end process;

    j_V_6_fu_127_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_V_5) + unsigned(ap_const_lv11_1));
    or_ln112_fu_146_p2 <= (trunc_ln1073_reg_274_pp0_iter3_reg or trunc_ln);
    t_V_1_fu_206_p3 <= 
        ap_const_lv10_3FF when (icmp_ln47_1_fu_191_p2(0) = '1') else 
        trunc_ln260_3_fu_197_p4;
    t_V_2_fu_214_p3 <= 
        tmp_V_reg_280_pp0_iter3_reg when (or_ln112_fu_146_p2(0) = '1') else 
        t_V_fu_174_p3;
    t_V_4_fu_225_p3 <= 
        t_V_1_fu_206_p3 when (and_ln116_fu_221_p2(0) = '1') else 
        t_V_2_fu_214_p3;
    t_V_fu_174_p3 <= 
        ap_const_lv10_3FF when (icmp_ln47_fu_159_p2(0) = '1') else 
        trunc_ln9_fu_165_p4;
    tmp_45_fu_182_p1 <= grp_fu_240_p2;
    tmp_45_fu_182_p4 <= tmp_45_fu_182_p1(25 downto 17);
    tmp_fu_150_p1 <= grp_fu_233_p2;
    tmp_fu_150_p4 <= tmp_fu_150_p1(25 downto 17);
    trunc_ln1073_fu_133_p1 <= ap_sig_allocacmp_j_V_5(1 - 1 downto 0);
    trunc_ln260_3_fu_197_p1 <= grp_fu_240_p2;
    trunc_ln260_3_fu_197_p4 <= trunc_ln260_3_fu_197_p1(16 downto 7);
    trunc_ln9_fu_165_p1 <= grp_fu_233_p2;
    trunc_ln9_fu_165_p4 <= trunc_ln9_fu_165_p1(16 downto 7);
    zext_ln232_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(imgInput2_data239_dout),26));
end behav;
