-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lsc_out_data243_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    lsc_out_data243_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    lsc_out_data243_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    lsc_out_data243_empty_n : IN STD_LOGIC;
    lsc_out_data243_read : OUT STD_LOGIC;
    aecin_data245_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    aecin_data245_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    aecin_data245_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    aecin_data245_full_n : IN STD_LOGIC;
    aecin_data245_write : OUT STD_LOGIC;
    mul_ln165 : IN STD_LOGIC_VECTOR (21 downto 0);
    offset_buffer_V_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_2_ce0 : OUT STD_LOGIC;
    offset_buffer_V_2_we0 : OUT STD_LOGIC;
    offset_buffer_V_2_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    offset_buffer_V_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_2_ce1 : OUT STD_LOGIC;
    offset_buffer_V_2_q1 : IN STD_LOGIC_VECTOR (8 downto 0);
    offset_buffer_V_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_1_ce0 : OUT STD_LOGIC;
    offset_buffer_V_1_we0 : OUT STD_LOGIC;
    offset_buffer_V_1_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    offset_buffer_V_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_1_ce1 : OUT STD_LOGIC;
    offset_buffer_V_1_q1 : IN STD_LOGIC_VECTOR (8 downto 0);
    zext_ln97 : IN STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_ce0 : OUT STD_LOGIC;
    offset_buffer_V_we0 : OUT STD_LOGIC;
    offset_buffer_V_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    offset_buffer_V_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_V_ce1 : OUT STD_LOGIC;
    offset_buffer_V_q1 : IN STD_LOGIC_VECTOR (8 downto 0);
    add_ln165 : IN STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of ISPPipeline_accel_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal icmp_ln165_reg_1517 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln165_reg_1517_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_reg_1532 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_reg_1532_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op53_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal icmp_ln179_reg_1532_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln165_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal aecin_data245_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal lsc_out_data243_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln97_cast_fu_287_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln97_cast_reg_1511 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln165_fu_353_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln165_reg_1521 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln170_fu_361_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln170_reg_1527 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln170_reg_1527_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln170_reg_1527_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln170_reg_1527_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln179_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln179_reg_1532_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1536 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1536_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1536_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1536_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_buffer_V_load_reg_1554 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln75_2_fu_391_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_2_reg_1559 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_buffer_V_1_load_reg_1564 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln75_5_fu_395_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_5_reg_1569 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_buffer_V_2_load_reg_1574 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln75_8_fu_399_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_8_reg_1579 : STD_LOGIC_VECTOR (1 downto 0);
    signal cmp221_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1584 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1584_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1584_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_load78_reg_1603 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i5868_load_reg_1608 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_s_fu_514_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_1614 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_522_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_reg_1619 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1624 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_4_fu_544_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_4_reg_1629 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln674_fu_550_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln674_reg_1635 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_V_fu_554_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_V_reg_1640 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_load77_reg_1645 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_170_load_reg_1650 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_7_fu_691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_reg_1656 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_699_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_reg_1661 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1666 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_8_fu_721_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_8_reg_1671 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln674_2_fu_727_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln674_2_reg_1677 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_V_1_fu_731_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_V_1_reg_1682 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_load_reg_1687 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_272_load_reg_1692 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_10_fu_868_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_reg_1698 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_876_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_reg_1703 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1708 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_12_fu_898_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_12_reg_1713 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln674_4_fu_904_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln674_4_reg_1719 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_V_2_fu_908_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_V_2_reg_1724 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_p_Val2_s_reg_276 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_phi_reg_pp0_iter1_p_Val2_s_reg_276 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_phi_reg_pp0_iter2_p_Val2_s_reg_276 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_phi_reg_pp0_iter3_p_Val2_s_reg_276 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_phi_reg_pp0_iter4_p_Val2_s_reg_276 : STD_LOGIC_VECTOR (29 downto 0);
    signal idxprom191_fu_403_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom233_fu_968_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_index_1_fu_126 : STD_LOGIC_VECTOR (11 downto 0);
    signal col_index_fu_375_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal empty_fu_130 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_1_fu_578_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0_045228_fu_134 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln674_fu_1057_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_102_fu_138 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_3_fu_755_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0_0452_132_fu_142 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln674_1_fu_1198_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_103_fu_146 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_5_fu_926_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0_0452_236_fu_150 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln674_2_fu_1339_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal conv_i5868_fu_154 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_fu_571_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_170_fu_158 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_2_fu_748_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_272_fu_162 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln218_4_fu_919_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_166 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln165_1_fu_339_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln170_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln75_2_fu_391_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln75_5_fu_395_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln75_8_fu_399_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1540_fu_424_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_fu_428_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_fu_428_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_2_fu_436_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1540_fu_424_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal q_2nd_err_scale7_2_fu_440_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal in_pixel_fu_420_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7by16_V_fu_446_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln75_fu_456_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln75_fu_459_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln75_fu_481_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln75_1_fu_463_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln75_fu_467_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln200_fu_493_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_1_fu_471_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_V_2_fu_487_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln200_1_fu_498_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal lhs_V_fu_504_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_fu_530_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1540_1_fu_595_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_30_fu_599_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_30_fu_599_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_13_fu_607_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1540_1_fu_595_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal q_2nd_err_scale7_1_fu_611_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal in_pixel_1_fu_585_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7by16_V_1_fu_617_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln75_7_fu_627_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln75_1_fu_630_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln75_5_fu_658_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln75_8_fu_634_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln75_3_fu_638_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln200_2_fu_670_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_4_fu_648_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_V_1_fu_664_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln200_3_fu_675_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal lhs_V_6_fu_681_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_2_fu_707_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1540_2_fu_772_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_36_fu_776_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_36_fu_776_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_22_fu_784_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1540_2_fu_772_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal q_2nd_err_scale7_fu_788_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal in_pixel_2_fu_762_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7by16_V_2_fu_794_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln75_14_fu_804_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln75_2_fu_807_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln75_10_fu_835_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln75_15_fu_811_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln75_6_fu_815_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln200_4_fu_847_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln75_7_fu_825_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_V_fu_841_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln200_5_fu_852_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal lhs_V_7_fu_858_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_4_fu_884_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub232_fu_963_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1541_1_fu_978_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln75_1_fu_986_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln75_2_fu_1003_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln75_5_fu_1011_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_4_fu_1000_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_3_fu_993_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1540_3_fu_975_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_2_fu_1021_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_6_fu_997_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln75_fu_1015_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_3_fu_1031_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_10_fu_1037_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln75_9_fu_1027_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_V_2_fu_1041_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_27_fu_1047_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_6_fu_1065_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln204_fu_981_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_29_fu_1077_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_fu_1072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1088_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_3_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln232_fu_1094_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_fu_1085_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1541_3_fu_1119_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln75_4_fu_1127_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln75_5_fu_1144_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln75_12_fu_1152_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_11_fu_1141_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_16_fu_1134_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1540_4_fu_1116_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_7_fu_1162_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_17_fu_1138_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln75_2_fu_1156_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_8_fu_1172_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_21_fu_1178_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln75_20_fu_1168_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_V_1_fu_1182_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_33_fu_1188_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_9_fu_1206_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln204_1_fu_1122_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_35_fu_1218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_1_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1088_1_fu_1229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_4_fu_1243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln232_2_fu_1235_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_2_fu_1226_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1541_5_fu_1260_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln75_7_fu_1268_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln75_8_fu_1285_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln75_19_fu_1293_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_18_fu_1282_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_23_fu_1275_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1540_5_fu_1257_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_12_fu_1303_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_24_fu_1279_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln75_4_fu_1297_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_13_fu_1313_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln75_26_fu_1319_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln75_25_fu_1309_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_V_fu_1323_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_39_fu_1329_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_12_fu_1347_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln204_2_fu_1263_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_41_fu_1359_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_2_fu_1354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1088_2_fu_1370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_5_fu_1384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln232_4_fu_1376_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_4_fu_1367_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_5_fu_1390_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_3_fu_1249_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_V_1_fu_1108_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_64 : BOOLEAN;
    signal ap_enable_state4_pp0_iter2_stage0 : BOOLEAN;
    signal ap_enable_operation_55 : BOOLEAN;
    signal ap_enable_state3_pp0_iter3_stage0 : BOOLEAN;
    signal ap_enable_operation_184 : BOOLEAN;
    signal ap_enable_state6_pp0_iter5_stage0 : BOOLEAN;
    signal ap_enable_operation_67 : BOOLEAN;
    signal ap_enable_operation_57 : BOOLEAN;
    signal ap_enable_operation_213 : BOOLEAN;
    signal ap_enable_operation_70 : BOOLEAN;
    signal ap_enable_operation_59 : BOOLEAN;
    signal ap_enable_operation_242 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ISPPipeline_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ISPPipeline_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter4_p_Val2_s_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if (((icmp_ln179_reg_1532_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln165_reg_1517_pp0_iter2_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter4_p_Val2_s_reg_276 <= lsc_out_data243_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_p_Val2_s_reg_276 <= ap_phi_reg_pp0_iter3_p_Val2_s_reg_276;
                end if;
            end if; 
        end if;
    end process;

    col_index_1_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    col_index_1_fu_126 <= ap_const_lv12_0;
                elsif (((icmp_ln165_fu_334_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    col_index_1_fu_126 <= col_index_fu_375_p2;
                end if;
            end if; 
        end if;
    end process;

    conv_i5868_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i5868_fu_154 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    conv_i5868_fu_154 <= select_ln218_fu_571_p3;
                end if;
            end if; 
        end if;
    end process;

    conv_i58_170_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i58_170_fu_158 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    conv_i58_170_fu_158 <= select_ln218_2_fu_748_p3;
                end if;
            end if; 
        end if;
    end process;

    conv_i58_272_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i58_272_fu_162 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    conv_i58_272_fu_162 <= select_ln218_4_fu_919_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_102_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_102_fu_138 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_102_fu_138 <= select_ln218_3_fu_755_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_103_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_103_fu_146 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_103_fu_146 <= select_ln218_5_fu_926_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_fu_130 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_fu_130 <= select_ln218_1_fu_578_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_166 <= ap_const_lv22_0;
                elsif (((icmp_ln165_fu_334_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_166 <= add_ln165_1_fu_339_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln165_reg_1517 <= icmp_ln165_fu_334_p2;
                    zext_ln97_cast_reg_1511(10 downto 0) <= zext_ln97_cast_fu_287_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                cmp221_reg_1584 <= cmp221_fu_409_p2;
                cmp221_reg_1584_pp0_iter3_reg <= cmp221_reg_1584;
                cmp221_reg_1584_pp0_iter4_reg <= cmp221_reg_1584_pp0_iter3_reg;
                cmp239_reg_1536_pp0_iter2_reg <= cmp239_reg_1536;
                cmp239_reg_1536_pp0_iter3_reg <= cmp239_reg_1536_pp0_iter2_reg;
                cmp239_reg_1536_pp0_iter4_reg <= cmp239_reg_1536_pp0_iter3_reg;
                conv_i5868_load_reg_1608 <= conv_i5868_fu_154;
                conv_i58_170_load_reg_1650 <= conv_i58_170_fu_158;
                conv_i58_272_load_reg_1692 <= conv_i58_272_fu_162;
                icmp_ln165_reg_1517_pp0_iter2_reg <= icmp_ln165_reg_1517;
                icmp_ln179_reg_1532_pp0_iter2_reg <= icmp_ln179_reg_1532;
                icmp_ln179_reg_1532_pp0_iter3_reg <= icmp_ln179_reg_1532_pp0_iter2_reg;
                icmp_ln179_reg_1532_pp0_iter4_reg <= icmp_ln179_reg_1532_pp0_iter3_reg;
                p_Result_10_reg_1698 <= add_ln200_5_fu_852_p2(1 downto 1);
                p_Result_7_reg_1656 <= add_ln200_3_fu_675_p2(1 downto 1);
                p_Result_s_reg_1614 <= add_ln200_1_fu_498_p2(1 downto 1);
                p_Val2_12_reg_1713 <= p_Val2_12_fu_898_p2;
                p_Val2_4_reg_1629 <= p_Val2_4_fu_544_p2;
                p_Val2_8_reg_1671 <= p_Val2_8_fu_721_p2;
                p_load77_reg_1645 <= empty_102_fu_138;
                p_load78_reg_1603 <= empty_fu_130;
                p_load_reg_1687 <= empty_103_fu_146;
                q_err_3rd_local_V_1_reg_1682 <= q_err_3rd_local_V_1_fu_731_p3;
                q_err_3rd_local_V_2_reg_1724 <= q_err_3rd_local_V_2_fu_908_p3;
                q_err_3rd_local_V_reg_1640 <= q_err_3rd_local_V_fu_554_p3;
                tmp_26_reg_1619 <= add_ln200_1_fu_498_p2(1 downto 1);
                tmp_32_reg_1661 <= add_ln200_3_fu_675_p2(1 downto 1);
                tmp_38_reg_1703 <= add_ln200_5_fu_852_p2(1 downto 1);
                tmp_8_reg_1708 <= quatizer_in_V_fu_841_p2(10 downto 2);
                tmp_reg_1624 <= quatizer_in_V_2_fu_487_p2(10 downto 2);
                tmp_s_reg_1666 <= quatizer_in_V_1_fu_664_p2(10 downto 2);
                trunc_ln170_reg_1527_pp0_iter2_reg <= trunc_ln170_reg_1527;
                trunc_ln170_reg_1527_pp0_iter3_reg <= trunc_ln170_reg_1527_pp0_iter2_reg;
                trunc_ln170_reg_1527_pp0_iter4_reg <= trunc_ln170_reg_1527_pp0_iter3_reg;
                trunc_ln674_2_reg_1677 <= trunc_ln674_2_fu_727_p1;
                trunc_ln674_4_reg_1719 <= trunc_ln674_4_fu_904_p1;
                trunc_ln674_reg_1635 <= trunc_ln674_fu_550_p1;
                trunc_ln75_2_reg_1559 <= trunc_ln75_2_fu_391_p1;
                trunc_ln75_5_reg_1569 <= trunc_ln75_5_fu_395_p1;
                trunc_ln75_8_reg_1579 <= trunc_ln75_8_fu_399_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_p_Val2_s_reg_276 <= ap_phi_reg_pp0_iter0_p_Val2_s_reg_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_p_Val2_s_reg_276 <= ap_phi_reg_pp0_iter1_p_Val2_s_reg_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_p_Val2_s_reg_276 <= ap_phi_reg_pp0_iter2_p_Val2_s_reg_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln165_fu_334_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cmp239_reg_1536 <= cmp239_fu_370_p2;
                icmp_ln179_reg_1532 <= icmp_ln179_fu_365_p2;
                select_ln165_reg_1521 <= select_ln165_fu_353_p3;
                trunc_ln170_reg_1527 <= trunc_ln170_fu_361_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                offset_buffer_V_1_load_reg_1564 <= offset_buffer_V_1_q1;
                offset_buffer_V_2_load_reg_1574 <= offset_buffer_V_2_q1;
                offset_buffer_V_load_reg_1554 <= offset_buffer_V_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                p_0_0_045228_fu_134 <= sext_ln674_fu_1057_p1;
                p_0_0_0452_132_fu_142 <= sext_ln674_1_fu_1198_p1;
                p_0_0_0452_236_fu_150 <= sext_ln674_2_fu_1339_p1;
            end if;
        end if;
    end process;
    zext_ln97_cast_reg_1511(11) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln165_1_fu_339_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_166) + unsigned(ap_const_lv22_1));
    add_ln200_1_fu_498_p2 <= std_logic_vector(unsigned(add_ln200_fu_493_p2) + unsigned(trunc_ln75_1_fu_471_p4));
    add_ln200_2_fu_670_p2 <= std_logic_vector(unsigned(trunc_ln75_3_fu_638_p4) + unsigned(trunc_ln75_5_reg_1569));
    add_ln200_3_fu_675_p2 <= std_logic_vector(unsigned(add_ln200_2_fu_670_p2) + unsigned(trunc_ln75_4_fu_648_p4));
    add_ln200_4_fu_847_p2 <= std_logic_vector(unsigned(trunc_ln75_6_fu_815_p4) + unsigned(trunc_ln75_8_reg_1579));
    add_ln200_5_fu_852_p2 <= std_logic_vector(unsigned(add_ln200_4_fu_847_p2) + unsigned(trunc_ln75_7_fu_825_p4));
    add_ln200_fu_493_p2 <= std_logic_vector(unsigned(trunc_ln75_fu_467_p1) + unsigned(trunc_ln75_2_reg_1559));
    add_ln204_1_fu_1122_p2 <= std_logic_vector(unsigned(tmp_s_reg_1666) + unsigned(zext_ln1541_3_fu_1119_p1));
    add_ln204_2_fu_1263_p2 <= std_logic_vector(unsigned(tmp_8_reg_1708) + unsigned(zext_ln1541_5_fu_1260_p1));
    add_ln204_fu_981_p2 <= std_logic_vector(unsigned(tmp_reg_1624) + unsigned(zext_ln1541_1_fu_978_p1));
    add_ln75_10_fu_835_p2 <= std_logic_vector(signed(sext_ln75_14_fu_804_p1) + signed(zext_ln75_2_fu_807_p1));
    add_ln75_12_fu_1303_p2 <= std_logic_vector(signed(sext_ln75_23_fu_1275_p1) + signed(sext_ln1540_5_fu_1257_p1));
    add_ln75_13_fu_1313_p2 <= std_logic_vector(signed(sext_ln75_24_fu_1279_p1) + signed(sub_ln75_4_fu_1297_p2));
    add_ln75_2_fu_1021_p2 <= std_logic_vector(signed(sext_ln75_3_fu_993_p1) + signed(sext_ln1540_3_fu_975_p1));
    add_ln75_3_fu_1031_p2 <= std_logic_vector(signed(sext_ln75_6_fu_997_p1) + signed(sub_ln75_fu_1015_p2));
    add_ln75_5_fu_658_p2 <= std_logic_vector(signed(sext_ln75_7_fu_627_p1) + signed(zext_ln75_1_fu_630_p1));
    add_ln75_7_fu_1162_p2 <= std_logic_vector(signed(sext_ln75_16_fu_1134_p1) + signed(sext_ln1540_4_fu_1116_p1));
    add_ln75_8_fu_1172_p2 <= std_logic_vector(signed(sext_ln75_17_fu_1138_p1) + signed(sub_ln75_2_fu_1156_p2));
    add_ln75_fu_481_p2 <= std_logic_vector(signed(sext_ln75_fu_456_p1) + signed(zext_ln75_fu_459_p1));

    aecin_data245_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, aecin_data245_full_n, icmp_ln179_reg_1532_pp0_iter4_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            aecin_data245_blk_n <= aecin_data245_full_n;
        else 
            aecin_data245_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    aecin_data245_din <= ((out_tmp_V_5_fu_1390_p3 & out_tmp_V_3_fu_1249_p3) & out_tmp_V_1_fu_1108_p3);

    aecin_data245_write_assign_proc : process(ap_enable_reg_pp0_iter5, icmp_ln179_reg_1532_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            aecin_data245_write <= ap_const_logic_1;
        else 
            aecin_data245_write <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, lsc_out_data243_empty_n, ap_predicate_op53_read_state3, aecin_data245_full_n, icmp_ln179_reg_1532_pp0_iter4_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = aecin_data245_full_n)) or ((ap_predicate_op53_read_state3 = ap_const_boolean_1) and (lsc_out_data243_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, lsc_out_data243_empty_n, ap_predicate_op53_read_state3, aecin_data245_full_n, icmp_ln179_reg_1532_pp0_iter4_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = aecin_data245_full_n)) or ((ap_predicate_op53_read_state3 = ap_const_boolean_1) and (lsc_out_data243_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, lsc_out_data243_empty_n, ap_predicate_op53_read_state3, aecin_data245_full_n, icmp_ln179_reg_1532_pp0_iter4_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = aecin_data245_full_n)) or ((ap_predicate_op53_read_state3 = ap_const_boolean_1) and (lsc_out_data243_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter3_assign_proc : process(lsc_out_data243_empty_n, ap_predicate_op53_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter3 <= ((ap_predicate_op53_read_state3 = ap_const_boolean_1) and (lsc_out_data243_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp0_stage0_iter5_assign_proc : process(aecin_data245_full_n, icmp_ln179_reg_1532_pp0_iter4_reg)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((icmp_ln179_reg_1532_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_0 = aecin_data245_full_n));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln165_fu_334_p2)
    begin
        if (((icmp_ln165_fu_334_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_184_assign_proc : process(cmp221_reg_1584_pp0_iter4_reg)
    begin
                ap_enable_operation_184 <= (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_213_assign_proc : process(cmp221_reg_1584_pp0_iter4_reg)
    begin
                ap_enable_operation_213 <= (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_242_assign_proc : process(cmp221_reg_1584_pp0_iter4_reg)
    begin
                ap_enable_operation_242 <= (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1);
    end process;

        ap_enable_operation_55 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_57 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_59 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_64 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_67 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_70 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state3_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state3_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state4_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state6_pp0_iter5_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5)
    begin
                ap_enable_state6_pp0_iter5_stage0 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_phi_reg_pp0_iter0_p_Val2_s_reg_276 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op53_read_state3_assign_proc : process(icmp_ln165_reg_1517_pp0_iter2_reg, icmp_ln179_reg_1532_pp0_iter2_reg)
    begin
                ap_predicate_op53_read_state3 <= ((icmp_ln179_reg_1532_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln165_reg_1517_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cmp221_fu_409_p2 <= "0" when (select_ln165_reg_1521 = ap_const_lv12_0) else "1";
    cmp239_fu_370_p2 <= "1" when (select_ln165_fu_353_p3 = zext_ln97_cast_reg_1511) else "0";
    col_index_fu_375_p2 <= std_logic_vector(unsigned(select_ln165_fu_353_p3) + unsigned(ap_const_lv12_1));
    icmp_ln165_fu_334_p2 <= "1" when (indvar_flatten_fu_166 = mul_ln165) else "0";
    icmp_ln170_fu_348_p2 <= "1" when (col_index_1_fu_126 = add_ln165) else "0";
    icmp_ln179_fu_365_p2 <= "1" when (unsigned(select_ln165_fu_353_p3) < unsigned(zext_ln97_cast_reg_1511)) else "0";
    idxprom191_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln165_reg_1521),64));
    idxprom233_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub232_fu_963_p2),64));
    in_pixel_1_fu_585_p4 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(19 downto 10);
    in_pixel_2_fu_762_p4 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(29 downto 20);
    in_pixel_fu_420_p1 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(10 - 1 downto 0);
    lhs_V_6_fu_681_p4 <= quatizer_in_V_1_fu_664_p2(11 downto 2);
    lhs_V_7_fu_858_p4 <= quatizer_in_V_fu_841_p2(11 downto 2);
    lhs_V_fu_504_p4 <= quatizer_in_V_2_fu_487_p2(11 downto 2);

    lsc_out_data243_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, lsc_out_data243_empty_n, ap_predicate_op53_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op53_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            lsc_out_data243_blk_n <= lsc_out_data243_empty_n;
        else 
            lsc_out_data243_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lsc_out_data243_read_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op53_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op53_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            lsc_out_data243_read <= ap_const_logic_1;
        else 
            lsc_out_data243_read <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_1_address0 <= idxprom233_fu_968_p1(11 - 1 downto 0);
    offset_buffer_V_1_address1 <= idxprom191_fu_403_p1(11 - 1 downto 0);

    offset_buffer_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            offset_buffer_V_1_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_V_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            offset_buffer_V_1_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_1_d0 <= p_0_0_0452_132_fu_142;

    offset_buffer_V_1_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, cmp221_reg_1584_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1))) then 
            offset_buffer_V_1_we0 <= ap_const_logic_1;
        else 
            offset_buffer_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_2_address0 <= idxprom233_fu_968_p1(11 - 1 downto 0);
    offset_buffer_V_2_address1 <= idxprom191_fu_403_p1(11 - 1 downto 0);

    offset_buffer_V_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            offset_buffer_V_2_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_V_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            offset_buffer_V_2_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_2_d0 <= p_0_0_0452_236_fu_150;

    offset_buffer_V_2_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, cmp221_reg_1584_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1))) then 
            offset_buffer_V_2_we0 <= ap_const_logic_1;
        else 
            offset_buffer_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_address0 <= idxprom233_fu_968_p1(11 - 1 downto 0);
    offset_buffer_V_address1 <= idxprom191_fu_403_p1(11 - 1 downto 0);

    offset_buffer_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            offset_buffer_V_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            offset_buffer_V_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_V_d0 <= p_0_0_045228_fu_134;

    offset_buffer_V_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, cmp221_reg_1584_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (cmp221_reg_1584_pp0_iter4_reg = ap_const_lv1_1))) then 
            offset_buffer_V_we0 <= ap_const_logic_1;
        else 
            offset_buffer_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1088_1_fu_1229_p2 <= (tmp_35_fu_1218_p3 or or_ln232_1_fu_1213_p2);
    or_ln1088_2_fu_1370_p2 <= (tmp_41_fu_1359_p3 or or_ln232_2_fu_1354_p2);
    or_ln1088_fu_1088_p2 <= (tmp_29_fu_1077_p3 or or_ln232_fu_1072_p2);
    or_ln232_1_fu_1213_p2 <= (p_Result_9_fu_1206_p3 or cmp239_reg_1536_pp0_iter4_reg);
    or_ln232_2_fu_1354_p2 <= (p_Result_12_fu_1347_p3 or cmp239_reg_1536_pp0_iter4_reg);
    or_ln232_3_fu_1102_p2 <= (or_ln232_fu_1072_p2 or or_ln1088_fu_1088_p2);
    or_ln232_4_fu_1243_p2 <= (or_ln232_1_fu_1213_p2 or or_ln1088_1_fu_1229_p2);
    or_ln232_5_fu_1384_p2 <= (or_ln232_2_fu_1354_p2 or or_ln1088_2_fu_1370_p2);
    or_ln232_fu_1072_p2 <= (p_Result_6_fu_1065_p3 or cmp239_reg_1536_pp0_iter4_reg);
    out_tmp_V_1_fu_1108_p3 <= 
        select_ln232_fu_1094_p3 when (or_ln232_3_fu_1102_p2(0) = '1') else 
        out_tmp_V_fu_1085_p1;
    out_tmp_V_2_fu_1226_p1 <= p_Val2_8_reg_1671(8 - 1 downto 0);
    out_tmp_V_3_fu_1249_p3 <= 
        select_ln232_2_fu_1235_p3 when (or_ln232_4_fu_1243_p2(0) = '1') else 
        out_tmp_V_2_fu_1226_p1;
    out_tmp_V_4_fu_1367_p1 <= p_Val2_12_reg_1713(8 - 1 downto 0);
    out_tmp_V_5_fu_1390_p3 <= 
        select_ln232_4_fu_1376_p3 when (or_ln232_5_fu_1384_p2(0) = '1') else 
        out_tmp_V_4_fu_1367_p1;
    out_tmp_V_fu_1085_p1 <= p_Val2_4_reg_1629(8 - 1 downto 0);
    p_Result_10_fu_868_p3 <= add_ln200_5_fu_852_p2(1 downto 1);
    p_Result_12_fu_1347_p3 <= p_Val2_12_reg_1713(9 downto 9);
    p_Result_6_fu_1065_p3 <= p_Val2_4_reg_1629(9 downto 9);
    p_Result_7_fu_691_p3 <= add_ln200_3_fu_675_p2(1 downto 1);
    p_Result_9_fu_1206_p3 <= p_Val2_8_reg_1671(9 downto 9);
    p_Result_s_fu_514_p3 <= add_ln200_1_fu_498_p2(1 downto 1);
    p_Val2_12_fu_898_p2 <= std_logic_vector(unsigned(lhs_V_7_fu_858_p4) + unsigned(zext_ln1541_4_fu_884_p1));
    p_Val2_4_fu_544_p2 <= std_logic_vector(unsigned(lhs_V_fu_504_p4) + unsigned(zext_ln1541_fu_530_p1));
    p_Val2_8_fu_721_p2 <= std_logic_vector(unsigned(lhs_V_6_fu_681_p4) + unsigned(zext_ln1541_2_fu_707_p1));
    q_2nd_err_scale7_1_fu_611_p2 <= std_logic_vector(signed(sext_ln75_13_fu_607_p1) - signed(sext_ln1540_1_fu_595_p1));
    q_2nd_err_scale7_2_fu_440_p2 <= std_logic_vector(signed(sext_ln75_2_fu_436_p1) - signed(sext_ln1540_fu_424_p1));
    q_2nd_err_scale7_fu_788_p2 <= std_logic_vector(signed(sext_ln75_22_fu_784_p1) - signed(sext_ln1540_2_fu_772_p1));
    q_2nd_err_scale7by16_V_1_fu_617_p4 <= q_2nd_err_scale7_1_fu_611_p2(11 downto 4);
    q_2nd_err_scale7by16_V_2_fu_794_p4 <= q_2nd_err_scale7_fu_788_p2(11 downto 4);
    q_2nd_err_scale7by16_V_fu_446_p4 <= q_2nd_err_scale7_2_fu_440_p2(11 downto 4);
    q_err_3rd_local_V_1_fu_731_p3 <= (p_Result_7_fu_691_p3 & trunc_ln674_2_fu_727_p1);
    q_err_3rd_local_V_2_fu_908_p3 <= (p_Result_10_fu_868_p3 & trunc_ln674_4_fu_904_p1);
    q_err_3rd_local_V_fu_554_p3 <= (p_Result_s_fu_514_p3 & trunc_ln674_fu_550_p1);
    quatizer_in_V_1_fu_664_p2 <= std_logic_vector(unsigned(add_ln75_5_fu_658_p2) + unsigned(sext_ln75_8_fu_634_p1));
    quatizer_in_V_2_fu_487_p2 <= std_logic_vector(unsigned(add_ln75_fu_481_p2) + unsigned(sext_ln75_1_fu_463_p1));
    quatizer_in_V_fu_841_p2 <= std_logic_vector(unsigned(add_ln75_10_fu_835_p2) + unsigned(sext_ln75_15_fu_811_p1));
    select_ln165_fu_353_p3 <= 
        ap_const_lv12_0 when (icmp_ln170_fu_348_p2(0) = '1') else 
        col_index_1_fu_126;
    select_ln218_1_fu_578_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        conv_i5868_fu_154;
    select_ln218_2_fu_748_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        q_err_3rd_local_V_1_fu_731_p3;
    select_ln218_3_fu_755_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        conv_i58_170_fu_158;
    select_ln218_4_fu_919_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        q_err_3rd_local_V_2_fu_908_p3;
    select_ln218_5_fu_926_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        conv_i58_272_fu_162;
    select_ln218_fu_571_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1536_pp0_iter3_reg(0) = '1') else 
        q_err_3rd_local_V_fu_554_p3;
    select_ln232_2_fu_1235_p3 <= 
        ap_const_lv8_0 when (or_ln232_1_fu_1213_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln232_4_fu_1376_p3 <= 
        ap_const_lv8_0 when (or_ln232_2_fu_1354_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln232_fu_1094_p3 <= 
        ap_const_lv8_0 when (or_ln232_fu_1072_p2(0) = '1') else 
        ap_const_lv8_FF;
    sext_ln1540_1_fu_595_p0 <= conv_i58_170_fu_158;
        sext_ln1540_1_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1540_1_fu_595_p0),12));

    sext_ln1540_2_fu_772_p0 <= conv_i58_272_fu_162;
        sext_ln1540_2_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1540_2_fu_772_p0),12));

        sext_ln1540_3_fu_975_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i5868_load_reg_1608),6));

        sext_ln1540_4_fu_1116_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i58_170_load_reg_1650),6));

        sext_ln1540_5_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i58_272_load_reg_1692),6));

    sext_ln1540_fu_424_p0 <= conv_i5868_fu_154;
        sext_ln1540_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1540_fu_424_p0),12));

        sext_ln674_1_fu_1198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_33_fu_1188_p4),9));

        sext_ln674_2_fu_1339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_39_fu_1329_p4),9));

        sext_ln674_fu_1057_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_1047_p4),9));

        sext_ln75_10_fu_1037_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_3_fu_1031_p2),7));

        sext_ln75_11_fu_1141_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_V_1_reg_1682),6));

        sext_ln75_12_fu_1152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_5_fu_1144_p4),6));

        sext_ln75_13_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_fu_599_p3),12));

        sext_ln75_14_fu_804_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_V_2_load_reg_1574),12));

        sext_ln75_15_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_V_2_fu_794_p4),12));

        sext_ln75_16_fu_1134_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_4_fu_1127_p3),6));

        sext_ln75_17_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load77_reg_1645),6));

        sext_ln75_18_fu_1282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_V_2_reg_1724),6));

        sext_ln75_19_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_8_fu_1285_p4),6));

        sext_ln75_1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_V_fu_446_p4),12));

        sext_ln75_20_fu_1168_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_7_fu_1162_p2),7));

        sext_ln75_21_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_8_fu_1172_p2),7));

        sext_ln75_22_fu_784_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_36_fu_776_p3),12));

        sext_ln75_23_fu_1275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_7_fu_1268_p3),6));

        sext_ln75_24_fu_1279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load_reg_1687),6));

        sext_ln75_25_fu_1309_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_12_fu_1303_p2),7));

        sext_ln75_26_fu_1319_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_13_fu_1313_p2),7));

        sext_ln75_2_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_24_fu_428_p3),12));

        sext_ln75_3_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_1_fu_986_p3),6));

        sext_ln75_4_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_V_reg_1640),6));

        sext_ln75_5_fu_1011_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln75_2_fu_1003_p4),6));

        sext_ln75_6_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load78_reg_1603),6));

        sext_ln75_7_fu_627_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_V_1_load_reg_1564),12));

        sext_ln75_8_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_V_1_fu_617_p4),12));

        sext_ln75_9_fu_1027_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln75_2_fu_1021_p2),7));

        sext_ln75_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_V_load_reg_1554),12));

    shl_ln75_1_fu_986_p3 <= (conv_i5868_load_reg_1608 & ap_const_lv2_0);
    shl_ln75_2_fu_1003_p4 <= ((p_Result_s_reg_1614 & trunc_ln674_reg_1635) & ap_const_lv2_0);
    shl_ln75_4_fu_1127_p3 <= (conv_i58_170_load_reg_1650 & ap_const_lv2_0);
    shl_ln75_5_fu_1144_p4 <= ((p_Result_7_reg_1656 & trunc_ln674_2_reg_1677) & ap_const_lv2_0);
    shl_ln75_7_fu_1268_p3 <= (conv_i58_272_load_reg_1692 & ap_const_lv2_0);
    shl_ln75_8_fu_1285_p4 <= ((p_Result_10_reg_1698 & trunc_ln674_4_reg_1719) & ap_const_lv2_0);
    sub232_fu_963_p2 <= std_logic_vector(unsigned(trunc_ln170_reg_1527_pp0_iter4_reg) + unsigned(ap_const_lv11_7FF));
    sub_ln75_2_fu_1156_p2 <= std_logic_vector(signed(sext_ln75_12_fu_1152_p1) - signed(sext_ln75_11_fu_1141_p1));
    sub_ln75_4_fu_1297_p2 <= std_logic_vector(signed(sext_ln75_19_fu_1293_p1) - signed(sext_ln75_18_fu_1282_p1));
    sub_ln75_fu_1015_p2 <= std_logic_vector(signed(sext_ln75_5_fu_1011_p1) - signed(sext_ln75_4_fu_1000_p1));
    sum_tmp_V_1_fu_1182_p2 <= std_logic_vector(signed(sext_ln75_21_fu_1178_p1) + signed(sext_ln75_20_fu_1168_p1));
    sum_tmp_V_2_fu_1041_p2 <= std_logic_vector(signed(sext_ln75_10_fu_1037_p1) + signed(sext_ln75_9_fu_1027_p1));
    sum_tmp_V_fu_1323_p2 <= std_logic_vector(signed(sext_ln75_26_fu_1319_p1) + signed(sext_ln75_25_fu_1309_p1));
    tmp_24_fu_428_p1 <= conv_i5868_fu_154;
    tmp_24_fu_428_p3 <= (tmp_24_fu_428_p1 & ap_const_lv3_0);
    tmp_26_fu_522_p3 <= add_ln200_1_fu_498_p2(1 downto 1);
    tmp_27_fu_1047_p4 <= sum_tmp_V_2_fu_1041_p2(6 downto 4);
    tmp_29_fu_1077_p3 <= add_ln204_fu_981_p2(8 downto 8);
    tmp_30_fu_599_p1 <= conv_i58_170_fu_158;
    tmp_30_fu_599_p3 <= (tmp_30_fu_599_p1 & ap_const_lv3_0);
    tmp_32_fu_699_p3 <= add_ln200_3_fu_675_p2(1 downto 1);
    tmp_33_fu_1188_p4 <= sum_tmp_V_1_fu_1182_p2(6 downto 4);
    tmp_35_fu_1218_p3 <= add_ln204_1_fu_1122_p2(8 downto 8);
    tmp_36_fu_776_p1 <= conv_i58_272_fu_162;
    tmp_36_fu_776_p3 <= (tmp_36_fu_776_p1 & ap_const_lv3_0);
    tmp_38_fu_876_p3 <= add_ln200_5_fu_852_p2(1 downto 1);
    tmp_39_fu_1329_p4 <= sum_tmp_V_fu_1323_p2(6 downto 4);
    tmp_41_fu_1359_p3 <= add_ln204_2_fu_1263_p2(8 downto 8);
    trunc_ln170_fu_361_p1 <= select_ln165_fu_353_p3(11 - 1 downto 0);
    trunc_ln674_2_fu_727_p1 <= quatizer_in_V_1_fu_664_p2(2 - 1 downto 0);
    trunc_ln674_4_fu_904_p1 <= quatizer_in_V_fu_841_p2(2 - 1 downto 0);
    trunc_ln674_fu_550_p1 <= quatizer_in_V_2_fu_487_p2(2 - 1 downto 0);
    trunc_ln75_1_fu_471_p4 <= q_2nd_err_scale7_2_fu_440_p2(5 downto 4);
    trunc_ln75_2_fu_391_p0 <= offset_buffer_V_q1;
    trunc_ln75_2_fu_391_p1 <= trunc_ln75_2_fu_391_p0(2 - 1 downto 0);
    trunc_ln75_3_fu_638_p4 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(11 downto 10);
    trunc_ln75_4_fu_648_p4 <= q_2nd_err_scale7_1_fu_611_p2(5 downto 4);
    trunc_ln75_5_fu_395_p0 <= offset_buffer_V_1_q1;
    trunc_ln75_5_fu_395_p1 <= trunc_ln75_5_fu_395_p0(2 - 1 downto 0);
    trunc_ln75_6_fu_815_p4 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(21 downto 20);
    trunc_ln75_7_fu_825_p4 <= q_2nd_err_scale7_fu_788_p2(5 downto 4);
    trunc_ln75_8_fu_399_p0 <= offset_buffer_V_2_q1;
    trunc_ln75_8_fu_399_p1 <= trunc_ln75_8_fu_399_p0(2 - 1 downto 0);
    trunc_ln75_fu_467_p1 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_276(2 - 1 downto 0);
    zext_ln1541_1_fu_978_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_reg_1619),9));
    zext_ln1541_2_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_699_p3),10));
    zext_ln1541_3_fu_1119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_reg_1661),9));
    zext_ln1541_4_fu_884_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_876_p3),10));
    zext_ln1541_5_fu_1260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_reg_1703),9));
    zext_ln1541_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_522_p3),10));
    zext_ln75_1_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_1_fu_585_p4),12));
    zext_ln75_2_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_2_fu_762_p4),12));
    zext_ln75_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_fu_420_p1),12));
    zext_ln97_cast_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln97),12));
end behav;
