-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_blackLevelCorrection_13_1080_1920_1_16_15_1_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_Src_rows_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    p_Src_rows_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    p_Src_rows_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    p_Src_rows_empty_n : IN STD_LOGIC;
    p_Src_rows_read : OUT STD_LOGIC;
    p_Src_cols_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    p_Src_cols_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    p_Src_cols_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    p_Src_cols_empty_n : IN STD_LOGIC;
    p_Src_cols_read : OUT STD_LOGIC;
    imgInput1_data238_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    imgInput1_data238_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput1_data238_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput1_data238_empty_n : IN STD_LOGIC;
    imgInput1_data238_read : OUT STD_LOGIC;
    imgInput2_data239_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    imgInput2_data239_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput2_data239_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgInput2_data239_full_n : IN STD_LOGIC;
    imgInput2_data239_write : OUT STD_LOGIC );
end;


architecture behav of ISPPipeline_accel_blackLevelCorrection_13_1080_1920_1_16_15_1_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_Src_rows_blk_n : STD_LOGIC;
    signal p_Src_cols_blk_n : STD_LOGIC;
    signal grp_fu_63_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal LoopCount_reg_79 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_idle : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_ready : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput1_data238_read : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_din : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_write : STD_LOGIC;
    signal grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_63_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_63_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_63_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal grp_fu_63_p00 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_63_p10 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ISPPipeline_accel_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgInput1_data238_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        imgInput1_data238_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgInput1_data238_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgInput1_data238_empty_n : IN STD_LOGIC;
        imgInput1_data238_read : OUT STD_LOGIC;
        imgInput2_data239_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        imgInput2_data239_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgInput2_data239_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgInput2_data239_full_n : IN STD_LOGIC;
        imgInput2_data239_write : OUT STD_LOGIC;
        LoopCount : IN STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component ISPPipeline_accel_mul_mul_11ns_11ns_22_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;



begin
    grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46 : component ISPPipeline_accel_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start,
        ap_done => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done,
        ap_idle => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_idle,
        ap_ready => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_ready,
        imgInput1_data238_dout => imgInput1_data238_dout,
        imgInput1_data238_num_data_valid => ap_const_lv2_0,
        imgInput1_data238_fifo_cap => ap_const_lv2_0,
        imgInput1_data238_empty_n => imgInput1_data238_empty_n,
        imgInput1_data238_read => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput1_data238_read,
        imgInput2_data239_din => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_din,
        imgInput2_data239_num_data_valid => ap_const_lv2_0,
        imgInput2_data239_fifo_cap => ap_const_lv2_0,
        imgInput2_data239_full_n => imgInput2_data239_full_n,
        imgInput2_data239_write => grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_write,
        LoopCount => LoopCount_reg_79);

    mul_mul_11ns_11ns_22_4_1_U64 : component ISPPipeline_accel_mul_mul_11ns_11ns_22_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 11,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_63_p0,
        din1 => grp_fu_63_p1,
        ce => grp_fu_63_ce,
        dout => grp_fu_63_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_ready = ap_const_logic_1)) then 
                    grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                LoopCount_reg_79 <= grp_fu_63_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_Src_rows_empty_n, p_Src_cols_empty_n, grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, p_Src_rows_empty_n, p_Src_cols_empty_n)
    begin
        if (((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done)
    begin
        if ((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, p_Src_rows_empty_n, p_Src_cols_empty_n)
    begin
                ap_block_state1 <= ((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start <= grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_ap_start_reg;

    grp_fu_63_ce_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_Src_rows_empty_n, p_Src_cols_empty_n, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and ((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))))) then 
            grp_fu_63_ce <= ap_const_logic_0;
        else 
            grp_fu_63_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_63_p0 <= grp_fu_63_p00(11 - 1 downto 0);
    grp_fu_63_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Src_cols_dout),22));
    grp_fu_63_p1 <= grp_fu_63_p10(11 - 1 downto 0);
    grp_fu_63_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Src_rows_dout),22));

    imgInput1_data238_read_assign_proc : process(grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput1_data238_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            imgInput1_data238_read <= grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput1_data238_read;
        else 
            imgInput1_data238_read <= ap_const_logic_0;
        end if; 
    end process;

    imgInput2_data239_din <= grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_din;

    imgInput2_data239_write_assign_proc : process(grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            imgInput2_data239_write <= grp_blackLevelCorrection_13_1080_1920_1_16_15_1_9_Pipeline_VITIS_LOOP_91_1_fu_46_imgInput2_data239_write;
        else 
            imgInput2_data239_write <= ap_const_logic_0;
        end if; 
    end process;


    p_Src_cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_Src_cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_Src_cols_blk_n <= p_Src_cols_empty_n;
        else 
            p_Src_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_Src_cols_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_Src_rows_empty_n, p_Src_cols_empty_n)
    begin
        if ((not(((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_Src_cols_read <= ap_const_logic_1;
        else 
            p_Src_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_Src_rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_Src_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_Src_rows_blk_n <= p_Src_rows_empty_n;
        else 
            p_Src_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_Src_rows_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_Src_rows_empty_n, p_Src_cols_empty_n)
    begin
        if ((not(((p_Src_cols_empty_n = ap_const_logic_0) or (p_Src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_Src_rows_read <= ap_const_logic_1;
        else 
            p_Src_rows_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
