-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_fifo_awb_17_17_1080_1920_1_s is
port (
    p_read : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (10 downto 0);
    demosaic_out_data241_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    demosaic_out_data241_empty_n : IN STD_LOGIC;
    demosaic_out_data241_read : OUT STD_LOGIC;
    p_read2 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (10 downto 0);
    ltm_in_data242_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    ltm_in_data242_full_n : IN STD_LOGIC;
    ltm_in_data242_write : OUT STD_LOGIC;
    hist0_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_0_ce0 : OUT STD_LOGIC;
    hist0_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_0_we0 : OUT STD_LOGIC;
    hist0_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_0_ce1 : OUT STD_LOGIC;
    hist0_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_0_we1 : OUT STD_LOGIC;
    hist0_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_1_ce0 : OUT STD_LOGIC;
    hist0_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_1_we0 : OUT STD_LOGIC;
    hist0_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_1_ce1 : OUT STD_LOGIC;
    hist0_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_1_we1 : OUT STD_LOGIC;
    hist0_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_2_ce0 : OUT STD_LOGIC;
    hist0_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_2_we0 : OUT STD_LOGIC;
    hist0_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist0_2_ce1 : OUT STD_LOGIC;
    hist0_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist0_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist0_2_we1 : OUT STD_LOGIC;
    hist1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_0_ce0 : OUT STD_LOGIC;
    hist1_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_0_we0 : OUT STD_LOGIC;
    hist1_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_0_ce1 : OUT STD_LOGIC;
    hist1_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_0_we1 : OUT STD_LOGIC;
    hist1_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_1_ce0 : OUT STD_LOGIC;
    hist1_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_1_we0 : OUT STD_LOGIC;
    hist1_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_1_ce1 : OUT STD_LOGIC;
    hist1_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_1_we1 : OUT STD_LOGIC;
    hist1_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_2_ce0 : OUT STD_LOGIC;
    hist1_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_2_we0 : OUT STD_LOGIC;
    hist1_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    hist1_2_ce1 : OUT STD_LOGIC;
    hist1_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hist1_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hist1_2_we1 : OUT STD_LOGIC;
    thresh : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read_ap_vld : IN STD_LOGIC;
    p_read1_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    p_read2_ap_vld : IN STD_LOGIC;
    p_read3_ap_vld : IN STD_LOGIC;
    thresh_ap_vld : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ISPPipeline_accel_fifo_awb_17_17_1080_1920_1_s is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_start : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_done : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_continue : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_idle : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_demosaic_out_data241_read : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_din : STD_LOGIC_VECTOR (29 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_write : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_we0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_we0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_we0 : STD_LOGIC;
    signal AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_start : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_done : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_continue : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_idle : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_impop_data1_read : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_din : STD_LOGIC_VECTOR (29 downto 0);
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_write : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0 : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0 : STD_LOGIC;
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0 : STD_LOGIC;
    signal impop_data_full_n : STD_LOGIC;
    signal impop_data_dout : STD_LOGIC_VECTOR (29 downto 0);
    signal impop_data_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal impop_data_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal impop_data_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ISPPipeline_accel_AWBhistogram_17_17_1080_1920_1_1_1024_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (10 downto 0);
        demosaic_out_data241_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        demosaic_out_data241_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        demosaic_out_data241_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        demosaic_out_data241_empty_n : IN STD_LOGIC;
        demosaic_out_data241_read : OUT STD_LOGIC;
        impop_data1_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        impop_data1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        impop_data1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        impop_data1_full_n : IN STD_LOGIC;
        impop_data1_write : OUT STD_LOGIC;
        histogram_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_0_ce0 : OUT STD_LOGIC;
        histogram_0_we0 : OUT STD_LOGIC;
        histogram_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        histogram_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_1_ce0 : OUT STD_LOGIC;
        histogram_1_we0 : OUT STD_LOGIC;
        histogram_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        histogram_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_2_ce0 : OUT STD_LOGIC;
        histogram_2_we0 : OUT STD_LOGIC;
        histogram_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ISPPipeline_accel_AWBNormalization_17_17_1080_1920_1_1_1024_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        impop_data1_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        impop_data1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        impop_data1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        impop_data1_empty_n : IN STD_LOGIC;
        impop_data1_read : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ltm_in_data242_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        ltm_in_data242_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        ltm_in_data242_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        ltm_in_data242_full_n : IN STD_LOGIC;
        ltm_in_data242_write : OUT STD_LOGIC;
        histogram_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_0_ce0 : OUT STD_LOGIC;
        histogram_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        histogram_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_1_ce0 : OUT STD_LOGIC;
        histogram_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        histogram_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        histogram_2_ce0 : OUT STD_LOGIC;
        histogram_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        thresh : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ISPPipeline_accel_fifo_w30_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (29 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (29 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    AWBhistogram_17_17_1080_1920_1_1_1024_U0 : component ISPPipeline_accel_AWBhistogram_17_17_1080_1920_1_1_1024_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_start,
        ap_done => AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_done,
        ap_continue => AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_continue,
        ap_idle => AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_idle,
        ap_ready => AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready,
        p_read => p_read,
        p_read1 => p_read1,
        demosaic_out_data241_dout => demosaic_out_data241_dout,
        demosaic_out_data241_num_data_valid => ap_const_lv2_0,
        demosaic_out_data241_fifo_cap => ap_const_lv2_0,
        demosaic_out_data241_empty_n => demosaic_out_data241_empty_n,
        demosaic_out_data241_read => AWBhistogram_17_17_1080_1920_1_1_1024_U0_demosaic_out_data241_read,
        impop_data1_din => AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_din,
        impop_data1_num_data_valid => impop_data_num_data_valid,
        impop_data1_fifo_cap => impop_data_fifo_cap,
        impop_data1_full_n => impop_data_full_n,
        impop_data1_write => AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_write,
        histogram_0_address0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_address0,
        histogram_0_ce0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0,
        histogram_0_we0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_we0,
        histogram_0_d0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_d0,
        histogram_1_address0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_address0,
        histogram_1_ce0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0,
        histogram_1_we0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_we0,
        histogram_1_d0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_d0,
        histogram_2_address0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_address0,
        histogram_2_ce0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0,
        histogram_2_we0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_we0,
        histogram_2_d0 => AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_d0);

    AWBNormalization_17_17_1080_1920_1_1_1024_U0 : component ISPPipeline_accel_AWBNormalization_17_17_1080_1920_1_1_1024_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_start,
        ap_done => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_done,
        ap_continue => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_continue,
        ap_idle => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_idle,
        ap_ready => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready,
        impop_data1_dout => impop_data_dout,
        impop_data1_num_data_valid => impop_data_num_data_valid,
        impop_data1_fifo_cap => impop_data_fifo_cap,
        impop_data1_empty_n => impop_data_empty_n,
        impop_data1_read => AWBNormalization_17_17_1080_1920_1_1_1024_U0_impop_data1_read,
        p_read => p_read2,
        p_read1 => p_read3,
        ltm_in_data242_din => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_din,
        ltm_in_data242_num_data_valid => ap_const_lv2_0,
        ltm_in_data242_fifo_cap => ap_const_lv2_0,
        ltm_in_data242_full_n => ltm_in_data242_full_n,
        ltm_in_data242_write => AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_write,
        histogram_0_address0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_address0,
        histogram_0_ce0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0,
        histogram_0_q0 => hist1_0_q0,
        histogram_1_address0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_address0,
        histogram_1_ce0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0,
        histogram_1_q0 => hist1_1_q0,
        histogram_2_address0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_address0,
        histogram_2_ce0 => AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0,
        histogram_2_q0 => hist1_2_q0,
        thresh => thresh);

    impop_data_U : component ISPPipeline_accel_fifo_w30_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_din,
        if_full_n => impop_data_full_n,
        if_write => AWBhistogram_17_17_1080_1920_1_1_1024_U0_impop_data1_write,
        if_dout => impop_data_dout,
        if_num_data_valid => impop_data_num_data_valid,
        if_fifo_cap => impop_data_fifo_cap,
        if_empty_n => impop_data_empty_n,
        if_read => AWBNormalization_17_17_1080_1920_1_1_1024_U0_impop_data1_read);





    ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_sync_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready <= ap_sync_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_continue <= ap_sync_continue;
    AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_start <= ((ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready xor ap_const_logic_1) and ap_start);
    AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_continue <= ap_sync_continue;
    AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_start <= ((ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready xor ap_const_logic_1) and ap_start);
    ap_done <= ap_sync_done;
    ap_idle <= (AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_idle and AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready <= (ap_sync_reg_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready or AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready);
    ap_sync_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready <= (ap_sync_reg_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready or AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready);
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_done and AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_done);
    ap_sync_ready <= (ap_sync_AWBhistogram_17_17_1080_1920_1_1_1024_U0_ap_ready and ap_sync_AWBNormalization_17_17_1080_1920_1_1_1024_U0_ap_ready);
    demosaic_out_data241_read <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_demosaic_out_data241_read;
    hist0_0_address0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_address0;
    hist0_0_address1 <= ap_const_lv10_0;
    hist0_0_ce0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0;
    hist0_0_ce1 <= ap_const_logic_0;
    hist0_0_d0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_d0;
    hist0_0_d1 <= ap_const_lv32_0;
    hist0_0_we0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_0_we0;
    hist0_0_we1 <= ap_const_logic_0;
    hist0_1_address0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_address0;
    hist0_1_address1 <= ap_const_lv10_0;
    hist0_1_ce0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0;
    hist0_1_ce1 <= ap_const_logic_0;
    hist0_1_d0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_d0;
    hist0_1_d1 <= ap_const_lv32_0;
    hist0_1_we0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_1_we0;
    hist0_1_we1 <= ap_const_logic_0;
    hist0_2_address0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_address0;
    hist0_2_address1 <= ap_const_lv10_0;
    hist0_2_ce0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0;
    hist0_2_ce1 <= ap_const_logic_0;
    hist0_2_d0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_d0;
    hist0_2_d1 <= ap_const_lv32_0;
    hist0_2_we0 <= AWBhistogram_17_17_1080_1920_1_1_1024_U0_histogram_2_we0;
    hist0_2_we1 <= ap_const_logic_0;
    hist1_0_address0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_address0;
    hist1_0_address1 <= ap_const_lv10_0;
    hist1_0_ce0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_0_ce0;
    hist1_0_ce1 <= ap_const_logic_0;
    hist1_0_d0 <= ap_const_lv32_0;
    hist1_0_d1 <= ap_const_lv32_0;
    hist1_0_we0 <= ap_const_logic_0;
    hist1_0_we1 <= ap_const_logic_0;
    hist1_1_address0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_address0;
    hist1_1_address1 <= ap_const_lv10_0;
    hist1_1_ce0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_1_ce0;
    hist1_1_ce1 <= ap_const_logic_0;
    hist1_1_d0 <= ap_const_lv32_0;
    hist1_1_d1 <= ap_const_lv32_0;
    hist1_1_we0 <= ap_const_logic_0;
    hist1_1_we1 <= ap_const_logic_0;
    hist1_2_address0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_address0;
    hist1_2_address1 <= ap_const_lv10_0;
    hist1_2_ce0 <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_histogram_2_ce0;
    hist1_2_ce1 <= ap_const_logic_0;
    hist1_2_d0 <= ap_const_lv32_0;
    hist1_2_d1 <= ap_const_lv32_0;
    hist1_2_we0 <= ap_const_logic_0;
    hist1_2_we1 <= ap_const_logic_0;
    ltm_in_data242_din <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_din;
    ltm_in_data242_write <= AWBNormalization_17_17_1080_1920_1_1_1024_U0_ltm_in_data242_write;
end behav;
